### ISSUE TITLE
Milestone 1 - User will be able to register a new account

### ISSUE THREAD

**Issue by xSynergyx** [xSynergyx/IT202011#1]
- [x] ID (not shown on UI), Username, email, password (other fields optional)
- [x] Password field should be 60 characters
- [x] Passwords should be hashed (plain text passwords lose points)
- [x] Email should be unique
- [x] Username should be unique
- [x] Form should have proper validations/checks for legitimate data:
- Email validation
- Username validation (length/required)
- Password validation (length minimum)
- Confirm password match
- [x] System should let user know if username or email is taken and allow the user to correct the error without wiping the form

**Comment by xSynergyx** [comment]
1f2fe86b62ad7fe901cfd131ca851ca53810d55e
