### ISSUE TITLE
Milestone 2 - User will be able to create a checking account

### ISSUE THREAD

**Issue by xSynergyx** [xSynergyx/IT202011#14]
- [x] System will generate a random 12 digit account number
- Must be unique
- [x] System will associate the account to the user
- [x] Account type will be set as checking
- [x] Will require a minimum deposit of $5 (from the world account)
- Entry will be recorded in the Transaction table in a transaction pair (per notes below)
- Account Balance will be updated based on SUM of BalanceChange of AccountSrc
- [x] User will see user-friendly error messages when appropriate
- [x] User will see user-friendly success message when account is created successfully
- Redirect user to their Accounts page
