### ISSUE TITLE
Milestone 3 - User will be able to transfer between their accounts

### ISSUE THREAD

**Issue by xSynergyx** [xSynergyx/IT202011#18]
- [x] Form should include a dropdown first AccountSrc and a dropdown for AccountDest (only accounts the user owns)
- [x] Form should include a field for a positive numeric value
- [x] System shouldn’t allow the user to transfer more funds than what’s available in AccountSrc
- [x] Form should allow the user to record a memo for the transaction
- [x] Each transaction is recorded as a transaction pair in the Transaction table
- These will reflect in the transaction history page
- [x] Show appropriate user-friendly error messages
- [x] Show user-friendly success messages
