### ISSUE TITLE
Milestone 3 - Transaction History page

### ISSUE THREAD

**Issue by xSynergyx** [xSynergyx/IT202011#19]
- [x] Will show the latest 10 transactions by default
- [ ] User will be able to filter transactions between two dates
- [ ] User will be able to filter transactions by type (deposit, withdraw, transfer)
- [x] Transactions should paginate results after the initial 10
