### ISSUE TITLE
Milestone 1 - User will be able to login to their account (given they enter the correct credentials)

### ISSUE THREAD

**Issue by xSynergyx** [xSynergyx/IT202011#2]
- [x] User can login with email or username
- [x] User should see friendly error messages when an account either doesn’t exist or if passwords don’t match
- [x] Logging in should fetch the user’s details (and roles) and save them into the session.
- [x] User will be directed to a dashboard page upon login
- Make sure data has been entered in both fields
- [x] Form should have proper validation
- This is a protected page (non-logged in users shouldn’t have access)

**Comment by xSynergyx** [comment]
09b7df2f1cb870263f5e6f045ca75bd1f079a9c8
