### ISSUE TITLE
Milestone 3 - User will be able to transfer funds to another user’s account

### ISSUE THREAD

**Issue by xSynergyx** [xSynergyx/IT202011#21]
- [x] Form should include a dropdown of the current user’s accounts (as AccountSrc)
- [x] Form should include a field for the user’s last name
- [x] Form should include a field for the last 4 digits of the user’s account number (to lookup AccountDest)
- [x] Form should include a field for a positive numerical value
- [x] Form should allow the user to record a memo for the transaction
- [x] System shouldn’t let the user transfer more than the balance of their account
- [x] System will lookup appropriate account based on user’s last name and the last 4 digits
- [x] Show appropriate user-friendly error messages
- [x] Show user-friendly success messages
- [x] Transaction will be recorded with the type as “ext-transfer”
- [x] Each transaction is recorded as a transaction pair in the Transaction table
- These will reflect in the transaction history page
