### ISSUE TITLE
Milestone 1 - User will be able to logout

### ISSUE THREAD

**Issue by xSynergyx** [xSynergyx/IT202011#3]
- [x] Logging out will redirect to login page
- [x] User should see a message that they’ve successfully logged out
- [x] Session should be destroyed (so the back button doesn’t allow them back in)

**Comment by xSynergyx** [comment]
1f2fe86b62ad7fe901cfd131ca851ca53810d55e
