### ISSUE TITLE
Milestone 1 - Basic Roles implemented

### ISSUE THREAD

**Issue by xSynergyx** [xSynergyx/IT202011#5]
- [x] Have a Roles table	(id, name, description, active)
- [x] Have a User Roles table (id, user_id, role_id, created)
- [x] Include a function to check if a user has a specific role (we won’t use it for this milestone but it should be usable in the future)

**Comment by xSynergyx** [comment]
f323f2f2b2c5747d126cbc1efcd35d6db721d90d
