### ISSUE TITLE
Milestone 1 - User will be able to edit their profile

### ISSUE THREAD

**Issue by xSynergyx** [xSynergyx/IT202011#9]
- [x] Changing username/email should properly check to see if it’s available before allowing the change
- [x] Any other fields should be properly validated
- [x] Allow password reset (only if the existing correct password is provided)

**Comment by xSynergyx** [comment]
6a52232c14e436ec0b83941649adb75a9f06819a
